apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
  namespace: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: us-central1-docker.pkg.dev/mando-host-project/real-world-devops/nodejs-app:v1
        ports:
        - containerPort: 8080